spring:
  datasource:
    account:
      url: jdbc:mysql://localhost:3307/account
      username: root
      password: 1234
    chat:
      url: jdbc:mysql://localhost:3307/chatdb
      username: root
      password: 1234
  data:
    redis:
      host: localhost
      port: 6380
      database: 0

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  application:
    name: chatserver
server:
  address: 0.0.0.0
