spring:
  datasource:
    account:
      url: jdbc:mysql://localhost:3307/account
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    chat:
      url: jdbc:mysql://localhost:3307/chatdb
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: chatserver
