spring:
  datasource:
    url: jdbc:h2:mem:chat
    username: gio
    password: 1234
  data:
    redis:
      host: localhost
      port: 6380
      database: 0

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  application:
    name: chatserver

SERVER_URL: localhost:8080