spring:
  datasource:
    url: jdbc:mysql://localhost:3307/chatdb
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6380
      database: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  application:
    name: chatserver
server:
  address: 0.0.0.0